### ISSUE TITLE
MC Not Tracking Which Sensors are Enabled/Disabled?

### ISSUE THREAD

**Issue by E3t1jump** [Engineering-3/MainController#5]
When the IMU multiple (3) sensors are enabled (and possibly because they are on the same register) MC only tells the firmware to stream two of them:

Example Sensor Config:

Numeric 6
Heading, Analog, 28, 1B, V/16
Signed
Streaming, 250

Numeric 7
Roll, Analog, 28, 1D, V/16
Signed
Streaming, 250

Numeric 8
Pitch, Analog, 28, 1F, V/16
Signed
Streaming, 250

Only Numeric 6 and Numeric 7 are streaming (only 2 I2C reads every 250ms, not 3 like there should be).

If the sensors are enabled one at a time (i.e. start with none enabled, then turn on one at a time, exiting from the sensors config window each time) it appears to work correctly - there are 3 I2C reads every 250ms and all 3 values are updating properly.

If all 3 sensors are then disabled, MC does not actually turn all 3 streaming commands off! Instead, one I2C read is still streaming every 250ms.

So the problem appears to be with how MC keeps track of what sensors are on/off, and what have changed as you enable/disable them in the sensors config window. It doesn't send the right number of streaming enable/disable commands to the Bfin whenever there is a change to the sensors config window.

**Comment by EmbeddedMan** [comment]
BFin software version test64 has fixed this issue. Testing by multiple parties shows the problem has been fixed. See this commit https://github.com/Engineering-3/RCM-BFin/commit/a0f0c081745ab86017c7c5fc574071a173bfc049
